version: "3"
services:
  backend:
    container_name: api-container
    image: ghcr.io/integrated-project-int221/backend:master

  frontend:
    container_name: frontend-container
    image: ghcr.io/integrated-project-int221/frontend:master
    depends_on: 
      - backend

  reverseproxy:
    container_name: reverseproxy-container
    image: nginx:1.19.10-alpine
    volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
       - "80:80"
    depends_on: 
       - frontend 

networks:
  default:
    external:
      name: database_myproduct-network
