version: "3"
services:
  frontend:
    image: ghcr.io/integrated-project-int221/frontend:master
    ports:
      - "8081:80"

networks:
  default:
    external:
      name: database_myproduct-network
